AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 120